name: CI

on:
  push:
    branches: [ master, gitActions ]
  pull_request:
    branches: [ master, gitActions ]
  schedule:
    # run every Monday at 5am UTC
    - cron: '0 5 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cancel_ci:
    name: Mandatory checks before CI
    runs-on: ubuntu-latest
    outputs:
      run_next: ${{ steps.skip_ci_step.outputs.run_next }}
    steps:
    - name: Check skip CI
      uses: OpenAstronomy/action-skip-ci@main
      id: skip_ci_step
      with:
        NO_FAIL: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # This should only run if we did not skip CI
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@ce177499ccf9fd2aded3b0426c97e5434c2e8a73
      if: steps.skip_ci_step.outputs.run_next == 'true'
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

  # The rest only run if above are done (unless cron only)
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: cancel_ci
    if: needs.cancel_ci.outputs.run_next == 'true'
    strategy:
      fail-fast: true
      matrix:
        include:

          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: codestyle

          - name: docs build
            os: ubuntu-latest
            python: 3.8
            toxenv: build_docs
            toxargs: -v

          - name: astropy dev with all dependencies with coverage
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-test-alldeps-devastropy-cov
            toxargs: -v

          - name: Python 3.7 with all optional dependencies (MacOS X)
            os: macos-latest
            python: 3.7
            toxenv: py37-test-alldeps
            toxargs: -v

          - name: Python 3.8 with mandatory dependencies (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38-test
            toxargs: -v

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: contains(matrix.toxenv,'-cov')
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml

  # This needs to be outside of matrix because if is not supported
  # for only one job in a matrix. But once that is supported, this can go
  # back to the matrix above.
  remote_data:
    name: Python 3.8 with all dependencies with remote data
    if: github.event_name == 'schedule' && github.repository == 'astropy/astroquery'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox -v -e py38-test-alldeps-devastropy -- --remote-data

  egg_info:
    name: egg_info with Python 3.7
    runs-on: ubuntu-latest
    needs: cancel_ci
    if: needs.cancel_ci.outputs.run_next == 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Run egg_info
      run: python setup.py egg_info
